import { ProposalPackage } from "../types/proposal";

export const PROPOSAL_CATALOG: ProposalPackage[] = [
  {
    id: "mountain-sanctuary",
    title: "Misty Mountain Sanctuary",
    subtitle: "Mahabaleshwar & Panchgani, Maharashtra",
    primaryDestination: "Mahabaleshwar",
    state: "Maharashtra",
    bestFor: "Peace, Nature & Reconnection",
    matchingMoods: ["Peace", "Nature", "Spiritual", "Family Time"],
    minBudget: 7000,
    typicalDuration: "3 Days / 2 Nights",
    whyItFitsTemplate: "Offers serene cliffside views, quiet forest walks, and cool misty climate away from city commotion. Fits your pace with private heritage estates and leisurely countryside exploration.",
    highlights: [
      "Boutique cliffside valley resort with heated infinity pool overlooking the Western Ghats.",
      "Private guided sunrise trek through Kate's Point and private strawberry farm tour.",
      "Artisan Maharashtrian candlelit dinner curated with organic local harvest.",
    ],
    experiences: [
      { title: "Valley Sunrise Walk", description: "Breathe in crisp mountain air across secluded viewing trails." },
      { title: "Artisan Dining", description: "Seasonal farm-to-table culinary feast." },
      { title: "Forest Sanctuary Retreat", description: "Quiet reading and wellness afternoon amidst lush pine groves." },
    ],
    basePricePerPerson: 9500,
  },
  {
    id: "coastal-escape",
    title: "The Coastal Reset",
    subtitle: "Tarkarli & Malvan, Maharashtra",
    primaryDestination: "Tarkarli",
    state: "Maharashtra",
    bestFor: "Ocean Waves, Water Sports & Sunsets",
    matchingMoods: ["Adventure", "Peace", "Fun", "Exploration"],
    minBudget: 6000,
    typicalDuration: "3 Days / 2 Nights",
    whyItFitsTemplate: "Combines white-sand beaches, quiet coastal hammocks, and certified marine adventures. Directly matches your desire for the sea with authentic coastal hospitality.",
    highlights: [
      "Private oceanfront cottage stay with direct shoreline access on Malvan Coast.",
      "PADI-assisted scuba diving & snorkeling experience around Sindhudurg Fort reef.",
      "Authentic coastal Malvani seafood feast prepared fresh by a master local chef.",
    ],
    experiences: [
      { title: "Scuba Exploration", description: "Vibrant coral reefs and clear coastal waters." },
      { title: "Sunset Dolphin Cruise", description: "Private boat excursion along the Karli backwaters." },
      { title: "Beachside Barbecue", description: "Fresh local catches with traditional Konkan spices under the stars." },
    ],
    basePricePerPerson: 8500,
  },
  {
    id: "vineyard-retreat",
    title: "Vineyard Sanctuary",
    subtitle: "Nashik Wine Country, Maharashtra",
    primaryDestination: "Nashik",
    state: "Maharashtra",
    bestFor: "Luxury, Romance & Slow Travel",
    matchingMoods: ["Luxury", "Romance", "Celebration", "Peace"],
    minBudget: 12000,
    typicalDuration: "2 Days / 1 Night or 3 Days",
    whyItFitsTemplate: "Surrounds you with rolling vineyards, exclusive barrel tasting, and Mediterranean-inspired villa living. Tailored for elevated relaxation, romantic dinners, and unwinding.",
    highlights: [
      "Luxury vineyard villa overlooking Gangapur lake with private tasting patio.",
      "Sommelier-guided barrel room tour and private vintage wine tasting session.",
      "Multi-course Italian and fusion pairing dinner under illuminated vineyard arbor.",
    ],
    experiences: [
      { title: "Sommelier Tour", description: "Exclusive access to private reserve cellars." },
      { title: "Lakefront Sunset", description: "Private waterside cabana with artisanal cheese board." },
      { title: "Spa & Rejuvenation", description: "Wine therapy massages and serene pool relaxation." },
    ],
    basePricePerPerson: 14000,
  },
  {
    id: "wildlife-expedition",
    title: "Wilderness Safari Odyssey",
    subtitle: "Tadoba-Andhari Tiger Reserve, Maharashtra",
    primaryDestination: "Tadoba",
    state: "Maharashtra",
    bestFor: "Thrills, Raw Nature & Big Cat Tracking",
    matchingMoods: ["Adventure", "Nature", "Exploration", "Surprise Me"],
    minBudget: 11000,
    typicalDuration: "3 Days / 2 Nights",
    whyItFitsTemplate: "Takes you deep into the teak and bamboo jungles of Central India with veteran naturalists. Designed for high adventure, wildlife photography, and luxury bush camp living.",
    highlights: [
      "Eco-luxury jungle safari lodge with private naturalist briefings and plunge pool.",
      "Exclusive core-zone open Gypsy safaris with top-tier forest track trackers.",
      "Campfire bush dinners with tribal folklore and stargazing through high-power optics.",
    ],
    experiences: [
      { title: "Open Gypsy Safaris", description: "Deep forest tracking for tigers, leopards, and sloth bears." },
      { title: "Birdwatching Walks", description: "Guided woodland walks around buffer-zone lakes." },
      { title: "Wilderness Dining", description: "Open-sky bush dinner with lantern lighting." },
    ],
    basePricePerPerson: 13500,
  },
  {
    id: "monsoon-valley-reset",
    title: "Monsoon Valley Escape",
    subtitle: "Lonavala & Matheran Foothills, Maharashtra",
    primaryDestination: "Lonavala",
    state: "Maharashtra",
    bestFor: "Weekend Reset, Friends Getaway & Quick Recharging",
    matchingMoods: ["Friends Getaway", "Fun", "Team Bonding", "Adventure"],
    minBudget: 5000,
    typicalDuration: "2 Days / 1 Night",
    whyItFitsTemplate: "A high-energy, convenient getaway designed for laughter, private pool villas, and lush green sceneries within an easy 2-hour drive from Mumbai or Pune.",
    highlights: [
      "Private 4-bedroom villa with private heated swimming pool and lawn barbecue setup.",
      "Private trail hike to secluded waterfall pools away from tourist crowds.",
      "Chef-on-demand service providing hot appetizers, bonfire setups, and music system.",
    ],
    experiences: [
      { title: "Private Villa Living", description: "Complete exclusivity with music and pool games." },
      { title: "Waterfall Trail", description: "Secret monsoon stream trail with natural plunge pools." },
      { title: "Lawn Barbecue", description: "Evening grilled skewers and bonfire acoustic jam." },
    ],
    basePricePerPerson: 6500,
  },
];
