import { ProposalPackage } from "../types/proposal";

export const PROPOSAL_CATALOG: ProposalPackage[] = [
  {
    id: "ujjain-temple-escape",
    title: "Sacred Ujjain & Omkareshwar Odyssey",
    subtitle: "Ujjain & Omkareshwar Jyotirlinga, Madhya Pradesh",
    primaryDestination: "Ujjain",
    state: "Madhya Pradesh",
    bestFor: "Bhasma Aarti, Spiritual Reconnection & Heritage",
    matchingMoods: ["Spiritual", "Peace", "Family Time", "Exploration"],
    minBudget: 7500,
    typicalDuration: "3 Days / 2 Nights",
    whyItFitsTemplate: "Immerses you into the divine presence of Lord Mahakal with VIP Darshan coordination, Shipra Ghat evening Aarti, and private air-conditioned train/car transfers. Crafted for soul-enriching peace.",
    highlights: [
      "Guaranteed VIP Bhasma Aarti reservation pass & Mahakaleshwar Corridor walkthrough.",
      "Private riverfront boat for evening Shipra River Grand Aarti with Vedic chants.",
      "Day tour to Omkareshwar Jyotirlinga island sanctuary via Narmada motor launch.",
    ],
    experiences: [
      { title: "Bhasma Aarti VIP Darshan", description: "Early morning sacred ritual access at Mahakaleshwar temple." },
      { title: "Shipra Ghat Sunset Aarti", description: "Private riverboat access during evening light offering." },
      { title: "Omkareshwar Island Tour", description: "Narmada River cruise to sacred Jyotirlinga shrine." },
    ],
    basePricePerPerson: 8900,
  },
  {
    id: "varanasi-sacred-ghats",
    title: "Varanasi & Sarnath Eternity Circuit",
    subtitle: "Varanasi Ghats & Sarnath Stupa, Uttar Pradesh",
    primaryDestination: "Varanasi",
    state: "Uttar Pradesh",
    bestFor: "Ganga Aarti, Ancient Culture & Photography",
    matchingMoods: ["Spiritual", "Culture", "Exploration", "Peace"],
    minBudget: 8500,
    typicalDuration: "4 Days / 3 Nights",
    whyItFitsTemplate: "Witness the timeless soul of India along the sacred Ganges. Features private wooden boat rides at dawn, Dashashwamedh Aarti, silk weaving heritage walks, and Sarnath Buddhist ruins.",
    highlights: [
      "Heritage ghat-side boutique stay with panoramic balcony views over the Ganges.",
      "Private hand-rowed sunrise boat cruise along Subah-e-Banaras ghats.",
      "Guided excursion to Sarnath Deer Park & Dhamek Stupa with expert historian.",
    ],
    experiences: [
      { title: "Subah-e-Banaras Boat", description: "Misty sunrise rowing along 84 ancient ghats." },
      { title: "Grand Ganga Aarti", description: "Reserved elevated seating for evening priest rituals." },
      { title: "Sarnath Heritage Walk", description: "Explore Lord Buddha's first sermon site & museum." },
    ],
    basePricePerPerson: 10500,
  },
  {
    id: "kerala-backwater-sanctuary",
    title: "Kerala Backwaters & Munnar Sanctuary",
    subtitle: "Alleppey & Munnar Hills, Kerala",
    primaryDestination: "Munnar",
    state: "Kerala",
    bestFor: "Private Houseboat, Lush Tea Gardens & Rejuvenation",
    matchingMoods: ["Nature", "Peace", "Romance", "Luxury"],
    minBudget: 11000,
    typicalDuration: "4 Days / 3 Nights",
    whyItFitsTemplate: "Blending mist-veiled tea estates in Munnar with a luxury private houseboat cruise through Alleppey backwaters. Perfect for serene relaxation and authentic Ayurvedic massage.",
    highlights: [
      "Overnight luxury private houseboat with personal chef and backwater deck.",
      "Boutique tea bungalow stay in Munnar overlooking Kolukkumalai peaks.",
      "Traditional Abhyanga Ayurvedic wellness session at certified spice garden resort.",
    ],
    experiences: [
      { title: "Private Houseboat Cruise", description: "Glide through quiet palm-fringed lagoons with custom Kerala cuisine." },
      { title: "Munnar Tea Estate Walk", description: "Private plucking and tasting session with tea master." },
      { title: "Ayurvedic Spa Reset", description: "60-minute herbal oil massage & steam bath." },
    ],
    basePricePerPerson: 13500,
  },
  {
    id: "kashmir-alpine-odyssey",
    title: "Royal Kashmir Alpine Odyssey",
    subtitle: "Srinagar, Gulmarg & Pahalgam, Jammu & Kashmir",
    primaryDestination: "Gulmarg",
    state: "Jammu & Kashmir",
    bestFor: "Snow Peaks, Gondola Rides & Heritage Luxury",
    matchingMoods: ["Luxury", "Romance", "Adventure", "Nature"],
    minBudget: 14000,
    typicalDuration: "5 Days / 4 Nights",
    whyItFitsTemplate: "An opulent journey across paradise on earth. Features carved cedar houseboats on Nigeen Lake, Phase II Gulmarg Gondola ride over snow fields, and Betaab Valley horse trails.",
    highlights: [
      "Heritage hand-carved luxury houseboat on quiet Nigeen Lake with butler service.",
      "VIP Gondola cable car tickets to Apharwat Peak at 13,780 feet.",
      "Private pine cottage stay in Pahalgam near Lidder River stream.",
    ],
    experiences: [
      { title: "Dal Lake Shikara Sunset", description: "Floating flower and spice market cruise." },
      { title: "Gulmarg Gondola Ride", description: "Ascend to high alpine snow bowls." },
      { title: "Lidder Valley Horse Trail", description: "Guided pony ride through pine meadows." },
    ],
    basePricePerPerson: 17500,
  },
  {
    id: "mountain-sanctuary",
    title: "Misty Mountain Sanctuary",
    subtitle: "Mahabaleshwar & Panchgani, Maharashtra",
    primaryDestination: "Mahabaleshwar",
    state: "Maharashtra",
    bestFor: "Peace, Nature & Reconnection",
    matchingMoods: ["Peace", "Nature", "Spiritual", "Family Time"],
    minBudget: 7000,
    typicalDuration: "3 Days / 2 Nights",
    whyItFitsTemplate: "Offers serene cliffside views, quiet forest walks, and cool misty climate away from city commotion. Fits your pace with private heritage estates and leisurely countryside exploration.",
    highlights: [
      "Boutique cliffside valley resort with heated infinity pool overlooking the Western Ghats.",
      "Private guided sunrise trek through Kate's Point and private strawberry farm tour.",
      "Artisan Maharashtrian candlelit dinner curated with organic local harvest.",
    ],
    experiences: [
      { title: "Valley Sunrise Walk", description: "Breathe in crisp mountain air across secluded viewing trails." },
      { title: "Artisan Dining", description: "Seasonal farm-to-table culinary feast." },
      { title: "Forest Sanctuary Retreat", description: "Quiet reading and wellness afternoon amidst lush pine groves." },
    ],
    basePricePerPerson: 9500,
  },
  {
    id: "coastal-escape",
    title: "The Coastal Reset",
    subtitle: "Tarkarli & Malvan, Maharashtra",
    primaryDestination: "Tarkarli",
    state: "Maharashtra",
    bestFor: "Ocean Waves, Water Sports & Sunsets",
    matchingMoods: ["Adventure", "Peace", "Fun", "Exploration"],
    minBudget: 6000,
    typicalDuration: "3 Days / 2 Nights",
    whyItFitsTemplate: "Combines white-sand beaches, quiet coastal hammocks, and certified marine adventures. Directly matches your desire for the sea with authentic coastal hospitality.",
    highlights: [
      "Private oceanfront cottage stay with direct shoreline access on Malvan Coast.",
      "PADI-assisted scuba diving & snorkeling experience around Sindhudurg Fort reef.",
      "Authentic coastal Malvani seafood feast prepared fresh by a master local chef.",
    ],
    experiences: [
      { title: "Scuba Exploration", description: "Vibrant coral reefs and clear coastal waters." },
      { title: "Sunset Dolphin Cruise", description: "Private boat excursion along the Karli backwaters." },
      { title: "Beachside Barbecue", description: "Fresh local catches with traditional Konkan spices under the stars." },
    ],
    basePricePerPerson: 8500,
  },
  {
    id: "vineyard-retreat",
    title: "Vineyard Sanctuary",
    subtitle: "Nashik Wine Country, Maharashtra",
    primaryDestination: "Nashik",
    state: "Maharashtra",
    bestFor: "Luxury, Romance & Slow Travel",
    matchingMoods: ["Luxury", "Romance", "Celebration", "Peace"],
    minBudget: 12000,
    typicalDuration: "2 Days / 1 Night or 3 Days",
    whyItFitsTemplate: "Surrounds you with rolling vineyards, exclusive barrel tasting, and Mediterranean-inspired villa living. Tailored for elevated relaxation, romantic dinners, and unwinding.",
    highlights: [
      "Luxury vineyard villa overlooking Gangapur lake with private tasting patio.",
      "Sommelier-guided barrel room tour and private vintage wine tasting session.",
      "Multi-course Italian and fusion pairing dinner under illuminated vineyard arbor.",
    ],
    experiences: [
      { title: "Sommelier Tour", description: "Exclusive access to private reserve cellars." },
      { title: "Lakefront Sunset", description: "Private waterside cabana with artisanal cheese board." },
      { title: "Spa & Rejuvenation", description: "Wine therapy massages and serene pool relaxation." },
    ],
    basePricePerPerson: 14000,
  },
  {
    id: "wildlife-expedition",
    title: "Wilderness Safari Odyssey",
    subtitle: "Tadoba-Andhari Tiger Reserve, Maharashtra",
    primaryDestination: "Tadoba",
    state: "Maharashtra",
    bestFor: "Thrills, Raw Nature & Big Cat Tracking",
    matchingMoods: ["Adventure", "Nature", "Exploration", "Surprise Me"],
    minBudget: 11000,
    typicalDuration: "3 Days / 2 Nights",
    whyItFitsTemplate: "Takes you deep into the teak and bamboo jungles of Central India with veteran naturalists. Designed for high adventure, wildlife photography, and luxury bush camp living.",
    highlights: [
      "Eco-luxury jungle safari lodge with private naturalist briefings and plunge pool.",
      "Exclusive core-zone open Gypsy safaris with top-tier forest track trackers.",
      "Campfire bush dinners with tribal folklore and stargazing through high-power optics.",
    ],
    experiences: [
      { title: "Open Gypsy Safaris", description: "Deep forest tracking for tigers, leopards, and sloth bears." },
      { title: "Birdwatching Walks", description: "Guided woodland walks around buffer-zone lakes." },
      { title: "Wilderness Dining", description: "Open-sky bush dinner with lantern lighting." },
    ],
    basePricePerPerson: 13500,
  },
];
